extends:
  - '@kurone-kito/eslint-config-base'
parserOptions:
  project:
    - './tsconfig.json'
root: true
rules:
  import/extensions:
    - error
    - never
    - css: ignorePackages
      js: ignorePackages
      json: ignorePackages
  n/no-missing-import: off
  n/no-unsupported-features/es-syntax: off
