ignores:
  - '**/node_modules/**'
  - .github/CODE_OF_CONDUCT*
  - Assets/**
  - Library/**
  - Logs/**
  - Packages/com.*/**
  - Packages/dev.*/**
  - ProjectSettings/**
  - Temp/**
  - UserSettings/**
