cache:
  cacheFormat: universal
  cacheLocation: node_modules/.cache/cspell/.cspell.cache
  cacheStrategy: metadata
  useCache: true
dictionaries:
  - css
  - dotnet
  - en_us
  - en-gb
  - game-development
  - gaming-terms
  - git
  - markdown
  - php
  - python
  - softwareTerms
  - unity
import:
  - '@kurone-kito/cspell-config'
ignorePaths:
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - Assets/TextMesh Pro
  - Assets/UdonSharp
  - Assets/XR
  - cspell.config.yml
  - Library
  - node_modules
  - npm
  - Packages/com.*
  - Packages/dev.*
  - Packages/*.json
  - ProjectSettings
  - storybook-static
ignoreRegExpList:
  - (avtr|wrld)_([0-9a-f]{8})-([0-9a-f]{4})-([0-9a-f]{4})-([0-9a-f]{4})-([0-9a-f]{12})
version: '0.2'
words:
  - atrous
  - denoiser
  - dwlt
  - lanchpadicons
  - kito
  - kuroné
  - Kuron
  - MSAA
  - scriban
  - solidjs
  - udon
  - unityyamlmerge
  - vinxi
  - vrchat
  - vrcsdk
  - vstuc
  - waivable
