cache:
  cacheFormat: universal
  cacheLocation: node_modules/.cache/cspell/.cspell.cache
  cacheStrategy: metadata
  useCache: true
dictionaries:
  - css
  - php
import:
  - '@kurone-kito/cspell-config'
ignorePaths:
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - Assets/TextMesh Pro
  - Assets/UdonSharp
  - Assets/XR
  - cspell.config.yml
  - node_modules
  - Packages/com.*
  - Packages/dev.*
  - Packages/*.json
  - ProjectSettings
  - storybook-static
ignoreRegExpList:
  - (avtr|wrld)_([0-9a-f]{8})-([0-9a-f]{4})-([0-9a-f]{4})-([0-9a-f]{4})-([0-9a-f]{12})
version: '0.2'
words:
  - atrous
  - clsx
  - csvg
  - daisyui
  - denoiser
  - dwlt
  - lanchpadicons
  - kito
  - kuroné
  - Kuron
  - MSAA
  - nunit
  - occludee
  - occluder
  - scriban
  - solidjs
  - spatialize
  - udon
  - ugui
  - vinxi
  - vrcsdk
  - vrchat
  - vstuc
  - waivable
