cache:
  cacheFormat: universal
  cacheLocation: node_modules/.cache/cspell/.cspell.cache
  cacheStrategy: metadata
  useCache: true
dictionaries:
  - cpp
  - csharp
  - css
  - dotnet
  - en-gb
  - en-us
  - fsharp
  - php
import:
  - '@kurone-kito/cspell-config'
ignorePaths:
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - Assets/TextMesh Pro
  - Assets/UdonSharp
  - Assets/XR
  - cspell.config.yml
  - node_modules
  - Packages/com.*
  - Packages/dev.*
  - Packages/*.json
  - ProjectSettings
ignoreRegExpList:
  - (avtr|wrld)_([0-9a-f]{8})-([0-9a-f]{4})-([0-9a-f]{4})-([0-9a-f]{4})-([0-9a-f]{12})
usePnP: true
version: '0.2'
words:
  - atrous
  - denoiser
  - kito
  - kuroné
  - Kuron
  - MSAA
  - nunit
  - occludee
  - occluder
  - scriban
  - spatialize
  - udon
  - vinxi
  - vrcsdk
  - vrchat
  - vstuc
  - waivable
