cache:
  cacheFormat: universal
  cacheLocation: node_modules/.cache/cspell/.cspell.cache
  cacheStrategy: metadata
  useCache: true
dictionaries:
  - css
  - flutter
  - game-development
  - gaming-terms
  - python
  - unity
import:
  - '@kurone-kito/cspell-config'
ignorePaths:
  - Assets/TextMesh Pro
  - Assets/UdonSharp
  - Assets/XR
  - Library
  - Packages/com.*
  - Packages/dev.*
  - Packages/*.json
  - ProjectSettings
  - storybook-static
ignoreRegExpList:
  - (avtr|wrld)_([0-9a-f]{8})-([0-9a-f]{4})-([0-9a-f]{4})-([0-9a-f]{4})-([0-9a-f]{12})
version: '0.2'
words:
  - atrous
  - denoiser
  - dwlt
  - lanchpadicons
  - kito
  - kuroné
  - Kuron
  - MSAA
  - scriban
  - solidjs
  - spatialize
  - udon
  - unityyamlmerge
  - vinxi
  - vrchat
  - vrcsdk
  - vstuc
  - waivable
