gitChecks: false
ignoreWorkspaceRootCheck: true
linkWorkspacePackages: true
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
packages:
  - nodePackages/*
