name: Build Repo Listing

env:
  listPublishDirectory: nodePackages/web/.output/public
  jsonGeneratedDirectory: Website
  pathToCi: ci

on:
  release:
    types:
      - created
      - deleted
      - edited
      - published
      - released
      - unpublished
  workflow_dispatch:
  workflow_run:
    types:
      - completed
    workflows:
      - Build Release

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write
  pages: write

# Allow one concurrent deployment
concurrency:
  cancel-in-progress: true
  group: pages

jobs:
  build-listing:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: build-listing
    runs-on: ubuntu-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout Local Repository
        uses: actions/checkout@v4
      - name: Checkout Automation Repository without removing prior checkouts
        uses: actions/checkout@v4
        with:
          clean: false
          path: ${{ env.pathToCi }}
          repository: vrchat-community/package-list-action
      - name: Pre-prepare the Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install the latest corepack explicitly
        run: npm install --force -g corepack@latest
      - name: Enable the corepack because of the pnpm
        run: corepack enable
      - name: Post-prepare the Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: ${{ !env.ACT && 'pnpm' || '' }}
          node-version-file: .node-version
      - env:
          HUSKY: 0
        name: Install the dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - env:
          BASE_PATH: /launchpad-icons
        name: Run the build to generate the website
        run: pnpm run build
      - name: Deploy the global.json file
        run: cp "${{ github.workspace }}/global.json" "${{ env.pathToCi }}/"
      - name: Load cached data from previous runs
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
          path: |
            ${{ env.pathToCi }}/.nuke/temp
            ~/.nuget/packages
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Build Package Version Listing with Nuke
        run: '"${{ env.pathToCi }}/build.cmd" BuildRepoListing --root "${{ env.pathToCi }}" --list-publish-directory "$GITHUB_WORKSPACE/${{ env.jsonGeneratedDirectory }}" --current-package-name "${{ vars.PACKAGE_NAME }}"'
      - name: Copy the generated index.json to the publish directory
        run: cp $GITHUB_WORKSPACE/${{ env.jsonGeneratedDirectory }}/index.json $GITHUB_WORKSPACE/${{ env.listPublishDirectory }}/
      - name: Prepare for GitHub Pages deployment
        uses: actions/configure-pages@v5
        with:
          enablement: true
          token: ${{ secrets.REPO_TOKEN }}
      - name: Upload the VPM Listing Website to GitHub Pages artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.listPublishDirectory }}
      - id: deployment
        name: Deploy the uploaded VPM Listing Website to GitHub Pages
        uses: actions/deploy-pages@v4
      - name: Trigger the action of the curation repository
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: build-listing
          repository: kurone-kito/vpm
          token: ${{ secrets.REPO_TOKEN }}
