name: Build Release

on:
  workflow_dispatch:

jobs:
  config:
    env:
      packagePath: Packages/${{ vars.PACKAGE_NAME }}
    name: configuration
    outputs:
      config_package: ${{ steps.config_package.outputs.configPackage }}
      stable_version: ${{ steps.stable-match.outputs.match }}
      upm_package: ${{ env.packagePath }}
      version: ${{ steps.version.outputs.value }}
    runs-on: ubuntu-latest
    steps:
      - name: Stages the pushed branch
        uses: actions/checkout@v4
      - id: config_package
        name: Ensure that required repository variable has been created for the Package
        run: |
          if [ "${{ vars.PACKAGE_NAME }}" != "" ]; then
            echo "configPackage=true" >> $GITHUB_OUTPUT;
          else
            echo "configPackage=false" >> $GITHUB_OUTPUT;
          fi
      - id: version
        name: Get the Package version based on the package.json file
        # cspell: disable-next-line
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq -r ".version" "${{ env.packagePath }}/package.json"
      - id: stable-match
        name: Detect whether the version is a stable release
        # cspell: disable-next-line
        uses: kaisugi/action-regex-match@v1.0.1
        with:
          flags: gm
          regex: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
          text: ${{ steps.version.outputs.value }}

  build-npm:
    name: build the NPM package
    needs: config
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Stages the pushed branch
        uses: actions/checkout@v4
      - name: Pre-prepare the Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install the latest corepack explicitly
        run: npm install --force -g corepack@latest
      - name: Enable the corepack because of the pnpm
        run: corepack enable
      - name: Post-prepare the Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: ${{ !env.ACT && 'pnpm' || '' }}
          node-version-file: .node-version
      - env:
          HUSKY: 0
        name: Install the dependencies
        run: pnpm install --prefer-frozen-lockfile
      - env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        name: Sets the token to deploying the NPM packages
        run: |
          cat << EOF > "${HOME}/.npmrc"
            @kurone-kito:registry=https://registry.npmjs.org/
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
      - env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ needs.config.outputs.stable_version == '' }}
        name: Publish the packages for pre-release
        run: pnpm run publish:next
      - env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ needs.config.outputs.stable_version != '' }}
        name: Publish the packages for release
        run: pnpm run publish

  build-upm:
    env:
      unityPackage:
      zipFile:
    if: needs.config.outputs.config_package == 'true'
    name: build the UPM package
    needs: config
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - id: gpg
        name: Import the GPG key
        # cspell: disable-next-line
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          trust_level: 5
      - name: Checkout Local Repository
        uses: actions/checkout@v4
      - name: copy the README and LICENSE files to the Package folder
        run: cp README.md LICENSE "${{ needs.config.outputs.upm_package }}"
      - name: Configure the Environment Variables needed for releasing the Package
        run: |
          echo "unityPackage=${{ vars.PACKAGE_NAME }}-${{ needs.config.outputs.version }}.unitypackage" >> $GITHUB_ENV
          echo "zipFile=${{ vars.PACKAGE_NAME }}-${{ needs.config.outputs.version }}.zip" >> $GITHUB_ENV
      - name: Zip the Package for release
        run: zip -r -9 "${{ github.workspace }}/${{ env.zipFile }}" .
        working-directory: '${{ needs.config.outputs.upm_package }}'
      - name: Build a list of .meta files for future use
        run: find "${{ needs.config.outputs.upm_package }}/" -name '*.meta' -type f >> metaList
      - name: Make a UnityPackage version of the Package for release
        uses: pCYSl5EDgo/create-unitypackage@v1
        with:
          include-files: metaList
          package-path: ${{ env.unityPackage }}
      - name: Zip the UnityPackage for release
        run: zip -r -9 "${{ env.unityPackage }}.zip" ${{ env.unityPackage }} LICENSE README.md
      - env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        name: Sign the artifacts
        run: |
          echo "${GPG_PASSPHRASE}" | gpg --batch -ab "${{ env.zipFile }}"
          echo "${GPG_PASSPHRASE}" | gpg --batch -ab "${{ env.unityPackage }}"
          echo "${GPG_PASSPHRASE}" | gpg --batch -ab "${{ env.unityPackage }}.zip"
      - id: tag_version
        name: Make a release tag of the version from the package.json file
        # cspell: disable-next-line
        uses: rickstaa/action-create-tag@v1
        with:
          tag: '${{ needs.config.outputs.version }}'
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Publish the Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.zipFile }}
            ${{ env.zipFile }}.asc
            ${{ env.unityPackage }}
            ${{ env.unityPackage }}.asc
            ${{ env.unityPackage }}.zip
            ${{ env.unityPackage }}.zip.asc
            ${{ needs.config.outputs.upm_package }}/package.json
          prerelease: ${{ needs.config.outputs.stable_version == '' }}
          tag_name: ${{ needs.config.outputs.version }}
