name: Mark stale issues
on:
  schedule:
    - cron: 0 0 * * *
permissions:
  issues: write
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          exempt-issue-labels: bug,enhancement
          exempt-pr-labels: bug,enhancement
          stale-issue-message: StaleBot labeled the issue as staled because there has been no activity.
          stale-issue-label: stale
